const APARTMENT_CREATE_SUCCESS = 'APARTMENT_CREATE_SUCCESS';
const APARTMENT_CREATE_FAIL = 'APARTMENT_CREATE_FAIL';
const GET_EXISTING_APARTMENT = 'GET_EXISTING_APARTMENT';
const GET_ALL_APARTMENTS_SUCCESS = 'GET_ALL_APARTMENTS_SUCCESS';
const START_APARTMENT_REQUEST = 'START_APARTMENT_REQUEST';
const STOP_APARTMENT_REQUEST = 'STOP_APARTMENT_REQUEST';

export default {
  APARTMENT_CREATE_SUCCESS,
  APARTMENT_CREATE_FAIL,
  GET_EXISTING_APARTMENT,
  GET_ALL_APARTMENTS_SUCCESS,
  START_APARTMENT_REQUEST,
  STOP_APARTMENT_REQUEST,
};
