const APARTMENT_CREATE_SUCCESS = 'APARTMENT_CREATE_SUCCESS';
const APARTMENT_CREATE_FAIL = 'APARTMENT_CREATE_FAIL';
const GET_EXISTING_APARTMENT = 'GET_EXISTING_APARTMENT';
const GET_ALL_APARTMENTS = 'GET_ALL_APARTMENTS';

export default {
  APARTMENT_CREATE_SUCCESS,
  APARTMENT_CREATE_FAIL,
  GET_EXISTING_APARTMENT,
  GET_ALL_APARTMENTS,
};
