const AUTH_ATTEMPT = 'AUTH_ATTEMPT'
const AUTH_SUCCESS = 'AUTH_SUCCESS'
const AUTH_FAIL = 'AUTH_FAIL'
const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAIL = 'LOGIN_FAIL'
const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT'
const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
const REGISTER_FAIL = 'REGISTER_FAIL'

export default {
  AUTH_ATTEMPT,
  AUTH_SUCCESS,
  AUTH_FAIL,
  LOGIN_ATTEMPT,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  REGISTER_ATTEMPT,
  REGISTER_SUCCESS,
  REGISTER_FAIL,
}
