const GET_ITEMS = 'GET_ITEMS';
const CREATE_ITEM = 'CREATE_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';
const ITEMS_LOADING = 'ITEMS_LOADING';

export default {
  GET_ITEMS,
  CREATE_ITEM,
  DELETE_ITEM,
  ITEMS_LOADING,
};
