const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
const SHOW_WARNING_MESSAGE = 'SHOW_WARNING_MESSAGE';
const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export default {
  SHOW_SUCCESS_MESSAGE,
  SHOW_WARNING_MESSAGE,
  SHOW_ERROR_MESSAGE,
  CLEAR_MESSAGE,
};
